### ISSUE TITLE
error to use maven clean install

### ISSUE THREAD

**Issue by zzj1213** [erdalkaraca/hi5#1]
[ERROR] Failed to resolve target definition /Users/hadoop/git/hi5/releng/de.metadocks.hi5.tycho.target/de.metadocks.hi5.tycho.target.target: Could not find "org.eclipse.emf.texo.sdk.feature.group/0.9.0.v201606022133" in the repositories of the current location -> [Help 1]
[ERROR]

**Comment by erdalkaraca** [comment]
Hi @zzj1213,
Thanks for trying out the project.
Unfortunately, there is not much instructions to get started with the project at the moment as I am still gathering best practices using Hi5, i.e. the project is still moving to find a direction to head towards.

**Comment by erdalkaraca** [comment]
@zzj1213 maven build works now

If you have any issues, let me know.
There is also a preliminary/simplistic demo product.
